name: openwardrobe
description: "An open source wardrobe management app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

flutter:
  uses-material-design: true


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.7.2
  connectivity_plus: ^6.1.2
  path_provider: ^2.1.5
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  supabase_auth_ui: ^0.5.4
  file_picker: ^8.3.5
  supabase_flutter: ^2.8.3
  brick_offline_first_with_supabase: ^1.3.0
  get_it: ^8.0.3
  sqflite: ^2.4.1
  brick_sqlite: ^3.2.2
  brick_supabase: ^1.4.1+1
  uuid: ^4.5.1
  sqflite_common_ffi: any
  brick_core: any
  sqflite_common_ffi_web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  brick_offline_first_with_supabase_build: ^1.0.0
  build_runner: ^2.4.6