// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20250213222641_up = [
  InsertTable('CommunityPostLike'),
  InsertTable('CommunityPostComment'),
  InsertTable('UseItem'),
  InsertTable('Outfit'),
  InsertTable('UserProfile'),
  InsertTable('WardrobeItem'),
  InsertTable('UseOutfit'),
  InsertTable('Brand'),
  InsertTable('OutfitItem'),
  InsertTable('Lookbook'),
  InsertTable('ItemMetadata'),
  InsertTable('LookbookItem'),
  InsertTable('ItemCategory'),
  InsertTable('CommunityPost'),
  InsertColumn('id', Column.varchar, onTable: 'CommunityPostLike', unique: true),
  InsertForeignKey('CommunityPostLike', 'CommunityPost', foreignKeyColumn: 'post_CommunityPost_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertForeignKey('CommunityPostLike', 'UserProfile', foreignKeyColumn: 'user_profile_UserProfile_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('created_at', Column.datetime, onTable: 'CommunityPostLike'),
  InsertColumn('id', Column.varchar, onTable: 'CommunityPostComment', unique: true),
  InsertForeignKey('CommunityPostComment', 'CommunityPost', foreignKeyColumn: 'post_CommunityPost_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertForeignKey('CommunityPostComment', 'UserProfile', foreignKeyColumn: 'user_profile_UserProfile_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('comment', Column.varchar, onTable: 'CommunityPostComment'),
  InsertColumn('created_at', Column.datetime, onTable: 'CommunityPostComment'),
  InsertColumn('id', Column.varchar, onTable: 'UseItem', unique: true),
  InsertForeignKey('UseItem', 'WardrobeItem', foreignKeyColumn: 'wardrobe_item_WardrobeItem_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('used_at', Column.datetime, onTable: 'UseItem'),
  InsertForeignKey('UseItem', 'UserProfile', foreignKeyColumn: 'user_profile_UserProfile_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('id', Column.varchar, onTable: 'Outfit', unique: true),
  InsertForeignKey('Outfit', 'UserProfile', foreignKeyColumn: 'user_profile_UserProfile_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('name', Column.varchar, onTable: 'Outfit'),
  InsertColumn('created_at', Column.datetime, onTable: 'Outfit'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Outfit'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Outfit'),
  InsertColumn('id', Column.varchar, onTable: 'UserProfile', unique: true),
  InsertColumn('username', Column.varchar, onTable: 'UserProfile'),
  InsertColumn('display_name', Column.varchar, onTable: 'UserProfile'),
  InsertColumn('bio', Column.varchar, onTable: 'UserProfile'),
  InsertColumn('avatar_url', Column.varchar, onTable: 'UserProfile'),
  InsertColumn('social_links', Column.varchar, onTable: 'UserProfile'),
  InsertColumn('is_public', Column.boolean, onTable: 'UserProfile'),
  InsertColumn('created_at', Column.datetime, onTable: 'UserProfile'),
  InsertColumn('updated_at', Column.datetime, onTable: 'UserProfile'),
  InsertColumn('id', Column.varchar, onTable: 'WardrobeItem', unique: true),
  InsertForeignKey('WardrobeItem', 'UserProfile', foreignKeyColumn: 'user_profile_UserProfile_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertForeignKey('WardrobeItem', 'Brand', foreignKeyColumn: 'brand_Brand_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertForeignKey('WardrobeItem', 'ItemCategory', foreignKeyColumn: 'item_category_ItemCategory_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('created_at', Column.datetime, onTable: 'WardrobeItem'),
  InsertColumn('updated_at', Column.datetime, onTable: 'WardrobeItem'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'WardrobeItem'),
  InsertColumn('image_path', Column.varchar, onTable: 'WardrobeItem'),
  InsertColumn('id', Column.varchar, onTable: 'UseOutfit', unique: true),
  InsertForeignKey('UseOutfit', 'Outfit', foreignKeyColumn: 'outfit_Outfit_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('used_at', Column.datetime, onTable: 'UseOutfit'),
  InsertForeignKey('UseOutfit', 'UserProfile', foreignKeyColumn: 'user_profile_UserProfile_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('id', Column.varchar, onTable: 'Brand', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Brand'),
  InsertForeignKey('Brand', 'UserProfile', foreignKeyColumn: 'user_profile_UserProfile_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('id', Column.varchar, onTable: 'OutfitItem', unique: true),
  InsertForeignKey('OutfitItem', 'Outfit', foreignKeyColumn: 'outfit_Outfit_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertForeignKey('OutfitItem', 'WardrobeItem', foreignKeyColumn: 'wardrobe_item_WardrobeItem_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('id', Column.varchar, onTable: 'Lookbook', unique: true),
  InsertForeignKey('Lookbook', 'UserProfile', foreignKeyColumn: 'user_profile_UserProfile_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('title', Column.varchar, onTable: 'Lookbook'),
  InsertColumn('description', Column.varchar, onTable: 'Lookbook'),
  InsertColumn('cover_image_url', Column.varchar, onTable: 'Lookbook'),
  InsertColumn('tags', Column.varchar, onTable: 'Lookbook'),
  InsertColumn('is_public', Column.boolean, onTable: 'Lookbook'),
  InsertColumn('created_at', Column.datetime, onTable: 'Lookbook'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Lookbook'),
  InsertColumn('id', Column.varchar, onTable: 'ItemMetadata', unique: true),
  InsertForeignKey('ItemMetadata', 'WardrobeItem', foreignKeyColumn: 'wardrobe_item_WardrobeItem_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('bought_for', Column.Double, onTable: 'ItemMetadata'),
  InsertColumn('currency', Column.varchar, onTable: 'ItemMetadata'),
  InsertColumn('purchase_date', Column.datetime, onTable: 'ItemMetadata'),
  InsertColumn('condition', Column.varchar, onTable: 'ItemMetadata'),
  InsertColumn('material', Column.varchar, onTable: 'ItemMetadata'),
  InsertColumn('size', Column.varchar, onTable: 'ItemMetadata'),
  InsertColumn('color', Column.varchar, onTable: 'ItemMetadata'),
  InsertColumn('notes', Column.varchar, onTable: 'ItemMetadata'),
  InsertColumn('created_at', Column.datetime, onTable: 'ItemMetadata'),
  InsertColumn('updated_at', Column.datetime, onTable: 'ItemMetadata'),
  InsertColumn('id', Column.varchar, onTable: 'LookbookItem', unique: true),
  InsertForeignKey('LookbookItem', 'Lookbook', foreignKeyColumn: 'lookbook_Lookbook_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('item_id', Column.varchar, onTable: 'LookbookItem'),
  InsertColumn('item_type', Column.varchar, onTable: 'LookbookItem'),
  InsertColumn('created_at', Column.datetime, onTable: 'LookbookItem'),
  InsertColumn('id', Column.varchar, onTable: 'ItemCategory', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'ItemCategory'),
  InsertColumn('id', Column.varchar, onTable: 'CommunityPost', unique: true),
  InsertForeignKey('CommunityPost', 'UserProfile', foreignKeyColumn: 'user_profile_UserProfile_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('content', Column.varchar, onTable: 'CommunityPost'),
  InsertColumn('image_url', Column.varchar, onTable: 'CommunityPost'),
  InsertColumn('is_public', Column.boolean, onTable: 'CommunityPost'),
  InsertColumn('created_at', Column.datetime, onTable: 'CommunityPost'),
  InsertColumn('updated_at', Column.datetime, onTable: 'CommunityPost'),
  CreateIndex(columns: ['id'], onTable: 'CommunityPostLike', unique: true),
  CreateIndex(columns: ['id'], onTable: 'CommunityPostComment', unique: true),
  CreateIndex(columns: ['id'], onTable: 'UseItem', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Outfit', unique: true),
  CreateIndex(columns: ['id'], onTable: 'UserProfile', unique: true),
  CreateIndex(columns: ['id'], onTable: 'WardrobeItem', unique: true),
  CreateIndex(columns: ['id'], onTable: 'UseOutfit', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Brand', unique: true),
  CreateIndex(columns: ['id'], onTable: 'OutfitItem', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Lookbook', unique: true),
  CreateIndex(columns: ['id'], onTable: 'ItemMetadata', unique: true),
  CreateIndex(columns: ['id'], onTable: 'LookbookItem', unique: true),
  CreateIndex(columns: ['id'], onTable: 'ItemCategory', unique: true),
  CreateIndex(columns: ['id'], onTable: 'CommunityPost', unique: true)
];

const List<MigrationCommand> _migration_20250213222641_down = [
  DropTable('CommunityPostLike'),
  DropTable('CommunityPostComment'),
  DropTable('UseItem'),
  DropTable('Outfit'),
  DropTable('UserProfile'),
  DropTable('WardrobeItem'),
  DropTable('UseOutfit'),
  DropTable('Brand'),
  DropTable('OutfitItem'),
  DropTable('Lookbook'),
  DropTable('ItemMetadata'),
  DropTable('LookbookItem'),
  DropTable('ItemCategory'),
  DropTable('CommunityPost'),
  DropColumn('id', onTable: 'CommunityPostLike'),
  DropColumn('post_CommunityPost_brick_id', onTable: 'CommunityPostLike'),
  DropColumn('user_profile_UserProfile_brick_id', onTable: 'CommunityPostLike'),
  DropColumn('created_at', onTable: 'CommunityPostLike'),
  DropColumn('id', onTable: 'CommunityPostComment'),
  DropColumn('post_CommunityPost_brick_id', onTable: 'CommunityPostComment'),
  DropColumn('user_profile_UserProfile_brick_id', onTable: 'CommunityPostComment'),
  DropColumn('comment', onTable: 'CommunityPostComment'),
  DropColumn('created_at', onTable: 'CommunityPostComment'),
  DropColumn('id', onTable: 'UseItem'),
  DropColumn('wardrobe_item_WardrobeItem_brick_id', onTable: 'UseItem'),
  DropColumn('used_at', onTable: 'UseItem'),
  DropColumn('user_profile_UserProfile_brick_id', onTable: 'UseItem'),
  DropColumn('id', onTable: 'Outfit'),
  DropColumn('user_profile_UserProfile_brick_id', onTable: 'Outfit'),
  DropColumn('name', onTable: 'Outfit'),
  DropColumn('created_at', onTable: 'Outfit'),
  DropColumn('updated_at', onTable: 'Outfit'),
  DropColumn('deleted_at', onTable: 'Outfit'),
  DropColumn('id', onTable: 'UserProfile'),
  DropColumn('username', onTable: 'UserProfile'),
  DropColumn('display_name', onTable: 'UserProfile'),
  DropColumn('bio', onTable: 'UserProfile'),
  DropColumn('avatar_url', onTable: 'UserProfile'),
  DropColumn('social_links', onTable: 'UserProfile'),
  DropColumn('is_public', onTable: 'UserProfile'),
  DropColumn('created_at', onTable: 'UserProfile'),
  DropColumn('updated_at', onTable: 'UserProfile'),
  DropColumn('id', onTable: 'WardrobeItem'),
  DropColumn('user_profile_UserProfile_brick_id', onTable: 'WardrobeItem'),
  DropColumn('brand_Brand_brick_id', onTable: 'WardrobeItem'),
  DropColumn('item_category_ItemCategory_brick_id', onTable: 'WardrobeItem'),
  DropColumn('created_at', onTable: 'WardrobeItem'),
  DropColumn('updated_at', onTable: 'WardrobeItem'),
  DropColumn('deleted_at', onTable: 'WardrobeItem'),
  DropColumn('image_path', onTable: 'WardrobeItem'),
  DropColumn('id', onTable: 'UseOutfit'),
  DropColumn('outfit_Outfit_brick_id', onTable: 'UseOutfit'),
  DropColumn('used_at', onTable: 'UseOutfit'),
  DropColumn('user_profile_UserProfile_brick_id', onTable: 'UseOutfit'),
  DropColumn('id', onTable: 'Brand'),
  DropColumn('name', onTable: 'Brand'),
  DropColumn('user_profile_UserProfile_brick_id', onTable: 'Brand'),
  DropColumn('id', onTable: 'OutfitItem'),
  DropColumn('outfit_Outfit_brick_id', onTable: 'OutfitItem'),
  DropColumn('wardrobe_item_WardrobeItem_brick_id', onTable: 'OutfitItem'),
  DropColumn('id', onTable: 'Lookbook'),
  DropColumn('user_profile_UserProfile_brick_id', onTable: 'Lookbook'),
  DropColumn('title', onTable: 'Lookbook'),
  DropColumn('description', onTable: 'Lookbook'),
  DropColumn('cover_image_url', onTable: 'Lookbook'),
  DropColumn('tags', onTable: 'Lookbook'),
  DropColumn('is_public', onTable: 'Lookbook'),
  DropColumn('created_at', onTable: 'Lookbook'),
  DropColumn('updated_at', onTable: 'Lookbook'),
  DropColumn('id', onTable: 'ItemMetadata'),
  DropColumn('wardrobe_item_WardrobeItem_brick_id', onTable: 'ItemMetadata'),
  DropColumn('bought_for', onTable: 'ItemMetadata'),
  DropColumn('currency', onTable: 'ItemMetadata'),
  DropColumn('purchase_date', onTable: 'ItemMetadata'),
  DropColumn('condition', onTable: 'ItemMetadata'),
  DropColumn('material', onTable: 'ItemMetadata'),
  DropColumn('size', onTable: 'ItemMetadata'),
  DropColumn('color', onTable: 'ItemMetadata'),
  DropColumn('notes', onTable: 'ItemMetadata'),
  DropColumn('created_at', onTable: 'ItemMetadata'),
  DropColumn('updated_at', onTable: 'ItemMetadata'),
  DropColumn('id', onTable: 'LookbookItem'),
  DropColumn('lookbook_Lookbook_brick_id', onTable: 'LookbookItem'),
  DropColumn('item_id', onTable: 'LookbookItem'),
  DropColumn('item_type', onTable: 'LookbookItem'),
  DropColumn('created_at', onTable: 'LookbookItem'),
  DropColumn('id', onTable: 'ItemCategory'),
  DropColumn('name', onTable: 'ItemCategory'),
  DropColumn('id', onTable: 'CommunityPost'),
  DropColumn('user_profile_UserProfile_brick_id', onTable: 'CommunityPost'),
  DropColumn('content', onTable: 'CommunityPost'),
  DropColumn('image_url', onTable: 'CommunityPost'),
  DropColumn('is_public', onTable: 'CommunityPost'),
  DropColumn('created_at', onTable: 'CommunityPost'),
  DropColumn('updated_at', onTable: 'CommunityPost'),
  DropIndex('index_CommunityPostLike_on_id'),
  DropIndex('index_CommunityPostComment_on_id'),
  DropIndex('index_UseItem_on_id'),
  DropIndex('index_Outfit_on_id'),
  DropIndex('index_UserProfile_on_id'),
  DropIndex('index_WardrobeItem_on_id'),
  DropIndex('index_UseOutfit_on_id'),
  DropIndex('index_Brand_on_id'),
  DropIndex('index_OutfitItem_on_id'),
  DropIndex('index_Lookbook_on_id'),
  DropIndex('index_ItemMetadata_on_id'),
  DropIndex('index_LookbookItem_on_id'),
  DropIndex('index_ItemCategory_on_id'),
  DropIndex('index_CommunityPost_on_id')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20250213222641',
  up: _migration_20250213222641_up,
  down: _migration_20250213222641_down,
)
class Migration20250213222641 extends Migration {
  const Migration20250213222641()
    : super(
        version: 20250213222641,
        up: _migration_20250213222641_up,
        down: _migration_20250213222641_down,
      );
}
